### ISSUE TITLE
车票票脚本使用版本咨询

### ISSUE THREAD

**Issue by ligyff** [dongdongtang/myrules#1]
你好，我在使用这个车票票脚本的时候遇到了一些问题，我想问一下你的这个脚本是用在什么版本，或者你现在的版本是多少。谢谢

**Comment by dongdongtang** [comment]
> 你好，我在使用这个车票票脚本的时候遇到了一些问题，我想问一下你的这个脚本是用在什么版本，或者你现在的版本是多少。谢谢
已经失效
